Repository mountain-sailors/stock-battle-front, pull requests merged in 2021-11, with the labels that each got.

#18 feat: add result, waiting room pages
  app/navigators/AppNavigator.tsx
  app/navigators/RootStackParams.ts
  app/screens/createRoom/AddRoomInfoScreen.tsx
  app/screens/createRoom/CompleteRoomScreen.tsx
  app/screens/createRoom/images/icon-moneybag.png
  app/screens/createRoom/images/icon-rate.png
  app/screens/createRoom/images/icon-wave.png
  app/screens/createRoom/images/img-partypopper.png
  app/screens/index.ts
  app/screens/room/ResultRoomScreen.tsx
  app/screens/room/WaitingRoomScreen.tsx
  app/screens/room/images/icon-horse-racing.png
  app/screens/room/images/icon-light.png
  app/screens/room/images/icon-trophy.png
Labels: feat

#21 feat: add utils to fetch api efficiently
  app/config/api.ts
  package.json
  yarn.lock
Labels: feat, chore

#22 feat: add running room, register stock, search stock page
  app/components/SearchInput.tsx
  app/components/index.ts
  app/navigators/AppNavigator.tsx
  app/navigators/RootStackParams.ts
  app/screens/index.ts
  app/screens/room/RegisterStockScreen.tsx
  app/screens/room/RunningRoomScreen.tsx
  app/screens/room/SearchStockScreen.tsx
  package.json
  yarn.lock
Labels: feat

#28 feat: implement login, signup api logic
  app/navigators/AppNavigator.tsx
  app/navigators/MainNavigator.tsx
  app/screens/initial/InitScreen.tsx
  app/screens/initial/LoginScreen.tsx
  app/screens/initial/SignupScreen.tsx
Labels: feat

#36 feat: refactor code related to auth, add mypage screen
  App.tsx
  app/components/Layout.tsx
  app/config/api.ts
  app/navigators/AppNavigator.tsx
  app/navigators/MainNavigator.tsx
  app/navigators/RootStackParams.ts
  app/screens/createRoom/AddRoomTitleScreen.tsx
  app/screens/createRoom/CompleteRoomScreen.tsx
  app/screens/initial/InitScreen.tsx
  app/screens/initial/LoginScreen.tsx
  app/screens/initial/SignupScreen.tsx
  app/screens/main/MainScreen.tsx
  app/screens/mypage/MypageScreen.tsx
  assets/avatar/avatar_1.png
  assets/avatar/avatar_2.png
  assets/avatar/avatar_3.png
  assets/avatar/avatar_4.png
  assets/avatar/avatar_5.png
  assets/images/character1.png
  assets/images/character2.png
  assets/images/character3.png
  assets/images/character4.png
Labels: feat

#37 feat: add stock api
  app/navigators/RootStackParams.ts
  app/screens/main/MainScreen.tsx
  app/screens/room/RegisterStockScreen.tsx
  app/screens/room/SearchStockScreen.tsx
  app/screens/room/WaitingRoomScreen.tsx
Labels: feat

#38 Fix/add room utils
  app/screens/createRoom/AddRoomTitleScreen.tsx
  app/screens/createRoom/CompleteRoomScreen.tsx
Labels: bug

#42 feat: add dashboard api and refactor some codes
  app/config/consts.ts
  app/config/utils.ts
  app/navigators/RootStackParams.ts
  app/screens/initial/images/avatar_1.png
  app/screens/initial/images/avatar_2.png
  app/screens/initial/images/avatar_3.png
  app/screens/initial/images/avatar_4.png
  app/screens/main/MainScreen.tsx
  app/screens/record/RecordScreen.tsx
  app/screens/room/RunningRoomScreen.tsx
  app/screens/room/SearchStockScreen.tsx
  app/screens/room/WaitingRoomScreen.tsx
  assets/images/character4.png
  package.json
  yarn.lock
Labels: feat
